### ISSUE TITLE
spiped service should subscribe to keyfile

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-spiped#2]
Updating the secret, doesn't restart the service.  It'd be great if it did.

Let me know if you're accepting PRs.  (This module hasn't been updated in a while, so perhaps you've moved on).

Thanks,
Alex

**Comment by alexjfisher** [comment]
@chriskuehl Hi!  I thought I'd reach out as I've been making some increasingly heavy modifications to this module in my own fork.  Next I plan to add some unit and acceptance tests.

If you're still using this module and would like to keep making your own forge releases, I could open PRs.  If not, I'm happy to migrate and release my fork under Vox Pupuli's `puppet` [namespace](https://forge.puppet.com/puppet).  (This gives me access to their excellent tooling, sponsored travis slots etc.)

Or if you're happy to have *your* fork maintained by the community, you could consider [migrating](https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli) it directly to the Vox Pupuli project.  You'd keep merge access in this scenario.

If you'd like to chat about any of these options, I'm usually around on the `#voxpupuli` freenode IRC [channel](irc://irc.freenode.net/voxpupuli) or on the puppet-community slack `#voxpupuli` [channel](https://puppetcommunity.slack.com/messages/voxpupuli/).

Thanks,
Alex (Vox Pupuli [PMC](https://voxpupuli.org/elections/) member)

**Comment by chriskuehl** [comment]
Hey @alexjfisher, sorry I missed your first ping -- somehow I was not "watching" this repo!

I'm happy to accept PRs, but as you noticed, I'm no longer personally using this module so am not really actively maintaining it. If you're interested in maintaining a fork, that sounds great to me. I'm also happy to give out commit access to this repo, but it sounds like Vox Pupuli might be a better idea.

Let me know if you need anything from me to get the repo moved over!

**Comment by alexjfisher** [comment]
I've sent you an invite to join the Vox github org.  This should allow you to transfer the repository over.  We find this is better for users than us forking a repo.

I'll make sure you keep commit access (although we do still ask that people don't merge their own PRs before they've been reviewed etc.).  If you're interested in helping with any of our other modules, we're always looking for volunteers.  Just let me know. :)

**Comment by chriskuehl** [comment]
Should be transferred now!
