### ISSUE TITLE
Deprecation request

### ISSUE THREAD

**Issue by TheMeier** [voxpupuli/puppet-spiped#40]
looking at the commit history and the state of the module I think this module should be deprecated

**Comment by alexjfisher** [comment]
Did you see https://github.com/voxpupuli/puppet-spiped/issues/38?

**Comment by alexjfisher** [comment]
Also https://github.com/voxpupuli/puppet_metadata/pull/124 and related PRs have been merged. This should help here.

**Comment by TheMeier** [comment]
Obviously I did not see #39 :facepalm:
